// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Generated from the docs/ folder structure — categories and order come
  // from each folder's _category_.json.
  workSamplesSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
